changelog:
  exclude:
    labels:
      - ignore-for-release
      - duplicate
      - invalid
      - wontfix
    authors:
      - dependabot[bot]
      - github-actions[bot]
  categories:
    - title: "🚀 New Features"
      labels:
        - enhancement
        - feature
    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix
    - title: "📖 Documentation"
      labels:
        - documentation
        - docs
    - title: "🔧 Maintenance"
      labels:
        - chore
        - dependencies
        - ci
    - title: "🔄 Other Changes"
      labels:
        - "*"
